version: '3.7'
services:
  grafana:
    image: grafana/grafana-enterprise:${GR_VERSION:-10.0.3}
    # image: grafana/grafana-enterprise:latest
    # image: grafana/grafana-enterprise:main
    ports:
      - '3000:3000'
    volumes:
      - ./:/var/lib/grafana/plugins/grafana-clickhouse-datasource
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - TERM=linux
      - GF_DEFAULT_APP_MODE=development
      - GF_ENTERPRISE_LICENSE_TEXT=$GF_ENTERPRISE_LICENSE_TEXT
    networks:
      - grafana

  clickhouse:
    image: 'clickhouse/clickhouse-server:${CLICKHOUSE_VERSION-23.2-alpine}'
    container_name: 'grafana-clickhouse-server'
    ports:
      - '8123:8123'
      - '9000:9000'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - grafana

networks:
  grafana: 
