version: '3.7'
services:
  grafana:
    image: grafana/grafana-enterprise:${GR_VERSION:-8.4.7}
    # image: grafana/grafana-enterprise:9.2.1
    # image: grafana/grafana-enterprise:latest
    # image: grafana/grafana-enterprise:main
    ports:
      - '3000:3000'
    volumes:
      - ./:/var/lib/grafana/plugins/grafana-clickhouse-datasource
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - TERM=linux
      - GF_DEFAULT_APP_MODE=development
      - GF_ENTERPRISE_LICENSE_TEXT=$GF_ENTERPRISE_LICENSE_TEXT
