import React, { useState } from 'react';
import { SelectableValue } from '@grafana/data';
import { RadioButtonGroup, ConfirmModal, InlineField, InlineFormLabel } from '@grafana/ui';
import { getQueryOptionsFromSql } from '../queryBuilder/utils';
import { generateSql } from 'data/sqlGenerator';
import labels from 'labels';
import { EditorType, CHQuery, CHSchemaQuery, defaultCHBuilderQuery } from 'types/sql';
import { QueryBuilderOptions } from 'types/queryBuilder';
import { mapQueryTypeToGrafanaFormat, stripBuilderOptions } from 'data/utils';
import { Datasource } from 'data/CHDatasource';
import { pluginVersion } from 'utils/version';

interface CHEditorTypeSwitcherProps {
  query: CHQuery;
  onChange: (query: CHQuery) => void;
  onRunQuery: () => void;
  datasource?: Datasource;
}

const options: Array<SelectableValue<EditorType>> = [
  { label: labels.types.EditorType.sql, value: EditorType.SQL },
  { label: labels.types.EditorType.builder, value: EditorType.Builder },
  { label: labels.types.EditorType.schema, value: EditorType.Schema },
];

/**
 * Component for switching between the SQL and Query Builder editors.
 */
export const EditorTypeSwitcher = (props: CHEditorTypeSwitcherProps) => {
  const { datasource, query, onChange } = props;
  const { label, tooltip, switcher, cannotConvert } = labels.components.EditorTypeSwitcher;
  const editorType: EditorType = query.editorType || EditorType.Builder;
  const [confirmModalState, setConfirmModalState] = useState<boolean>(false);
  const [cannotConvertModalState, setCannotConvertModalState] = useState<boolean>(false);
  const [errorMessage, setErrorMessage] = useState<string>('');
  const onEditorTypeChange = (editorType: EditorType, confirmed = false) => {
    // TODO: component state has updated, but not local state.
    if (query.editorType === EditorType.SQL && editorType === EditorType.Builder && !confirmed) {
      try {
        getQueryOptionsFromSql(query.rawSql, query.queryType, datasource);
        setConfirmModalState(true);
      } catch (err) {
        setCannotConvertModalState(true);
        setErrorMessage((err as Error).message);
      }
    } else {
      let builderOptions: QueryBuilderOptions;
      switch (query.editorType) {
        case EditorType.Builder:
          builderOptions = query.builderOptions;
          break;
        case EditorType.Schema:
          builderOptions = query.meta?.builderOptions || defaultCHBuilderQuery.builderOptions;
          break;
        case EditorType.SQL:
          try {
            builderOptions = getQueryOptionsFromSql(query.rawSql, query.queryType, datasource) as QueryBuilderOptions;
          } catch (err) {
            builderOptions = defaultCHBuilderQuery.builderOptions;
          }
          break;
        default:
          builderOptions = defaultCHBuilderQuery.builderOptions;
          break;
      }

      if (editorType === EditorType.Schema) {
        const baseQuery = stripBuilderOptions(query);

        onChange({
          ...baseQuery,
          // Without this, migrateCHQuery sees rawSql with no pluginVersion, treats the
          // query as pre-v4, and rewrites it back to EditorType.SQL on the next render.
          pluginVersion,
          editorType: EditorType.Schema,
          queryType: builderOptions.queryType,
          rawSql: query.rawSql || generateSql(builderOptions),
          format: mapQueryTypeToGrafanaFormat(builderOptions.queryType),
          meta: { builderOptions },
          schemaExplorer: (query as CHSchemaQuery).schemaExplorer || {
            database: builderOptions.database || undefined,
            table: builderOptions.table || undefined,
          },
        });
      } else if (editorType === EditorType.SQL) {
        onChange({
          ...query,
          pluginVersion,
          editorType: EditorType.SQL,
          queryType: builderOptions.queryType,
          // SQL already generated by the schema explorer is carried over as-is.
          rawSql: query.editorType === EditorType.Schema ? query.rawSql : generateSql(builderOptions),
          format: mapQueryTypeToGrafanaFormat(builderOptions.queryType),
          meta: { builderOptions },
        });
      } else if (editorType === EditorType.Builder) {
        onChange({
          ...query,
          pluginVersion,
          editorType: EditorType.Builder,
          queryType: builderOptions.queryType,
          rawSql: generateSql(builderOptions),
          builderOptions,
        });
      }
    }
  };
  const onConfirmEditorTypeChange = () => {
    onEditorTypeChange(EditorType.Builder, true);
    setConfirmModalState(false);
    setCannotConvertModalState(false);
  };
  return (
    <span>
      <InlineField
        label={
          <InlineFormLabel width={8} className="query-keyword" tooltip={tooltip}>
            {label}
          </InlineFormLabel>
        }
      >
        <RadioButtonGroup options={options} value={editorType} onChange={(e) => onEditorTypeChange(e)} />
      </InlineField>
      <ConfirmModal
        isOpen={confirmModalState}
        title={switcher.title}
        body={switcher.body}
        confirmText={switcher.confirmText}
        dismissText={switcher.dismissText}
        onConfirm={onConfirmEditorTypeChange}
        onDismiss={() => setConfirmModalState(false)}
      />
      <ConfirmModal
        title={cannotConvert.title}
        body={`${errorMessage}\n${cannotConvert.message}`}
        isOpen={cannotConvertModalState}
        onConfirm={onConfirmEditorTypeChange}
        confirmText={switcher.confirmText}
        onDismiss={() => setCannotConvertModalState(false)}
      />
    </span>
  );
};
