name: Scheduled Cloud E2E tests

on:
  # Run nightly against the shared Cloud instance
  schedule:
    - cron: '0 9 * * *' # Daily at 09:00 UTC

  # Allow engineers to run Cloud E2E on-demand (useful for debugging)
  workflow_dispatch:

jobs:
  playwright-cloud:
    uses: grafana/data-sources-ci-workflows/.github/workflows/playwright-cloud.yml@cba42f3de6fce37bb278584f910d0e733ec03e35 # main
    secrets: inherit
    with:
      pdc-network-name: datasources-pdc-network-aws-datasourcese2e
      repo-secrets: |
        DS_INSTANCE_HOST=ds-instance:host
        DS_INSTANCE_PASSWORD=ds-instance:password
        DS_INSTANCE_PORT=ds-instance:port
        DS_INSTANCE_USERNAME=ds-instance:username
