name: Compatibility check
on:
  pull_request:

jobs:
  compatibilitycheck:
    permissions:
      contents: read
      pull-requests: write # needed for the `comment-pr: yes` step below
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci
      - name: Build plugin
        run: npm run build
      - name: Compatibility check
        uses: grafana/plugin-actions/is-compatible@4698961fa64137fcac207108397ebe8a738a33d1
        with:
          module: './src/module.ts'
          comment-pr: 'yes'
          skip-comment-if-compatible: 'yes'
          fail-if-incompatible: 'no'
          targets: '@grafana/data,@grafana/ui,@grafana/runtime,@grafana/e2e-selectors'
