name: Integration tests

on:
  push:
    branches:
      - v1
      - main
  pull_request:
    branches:
      - v1
      - main
  schedule:
    - cron: '0 9 1 * *'

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        clickhouse:
          - 24.8
          - 25.3
          - 25.5
          - 25.6
          - 25.7
          - latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: 'go.mod'

      - name: Build backend
        uses: magefile/mage-action@07f03e200d4d168576899f4d31ffebfa8fb195ff
        with:
          args: buildAll
          version: latest

      - name: Run integration tests
        run: CLICKHOUSE_VERSION=${{ matrix.clickhouse }} go test -v -tags=integration ./...
