name: Run commands when issues are labeled
on:
  issues:
    types: [labeled]
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Actions
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          repository: "grafana/grafana-github-actions"
          path: ./actions
          ref: main
          persist-credentials: false

      - name: Install Actions
        run: npm install --production --prefix ./actions

      - id: get-github-token
        uses: grafana/shared-workflows/actions/create-github-app-token@create-github-app-token/v0.3.1
        with:
          github_app: grafana-oss-big-tent

      - name: Run Commands
        uses: ./actions/commands
        with:
          token: ${{ steps.get-github-token.outputs.token }}
          configPath: issue_commands
